# Uncomment the next line to define a global platform for your project
# platform :ios, '14.0'

target 'ProductsP' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ProductsP

    pod 'RxSwift'
    pod 'RxCocoa'
    pod 'SwiftLint'

  end

  target 'ProductsPTests' do
    inherit! :search_paths
    # Pods for testing

    pod 'RxBlocking'
    pod 'RxTest'

  end

  target 'ProductsPUITests' do
    # Pods for testing

end
